/**
 * Operational Transformation (OT) & Sync Simulation Engine
 * Models eventual consistency, concurrent edits conflict resolution, and generates trace logs.
 */

export class OTEngine {
  constructor(documentId, initialContent = '') {
    this.documentId = documentId;
    this.revision = 10; // Start at revision 10
    this.history = []; // History of committed operations { revision, op }
    this.logs = []; // Conflict logs [{ timestamp, message, type: 'info'|'conflict'|'sync' }]
  }

  log(message, type = 'info') {
    this.logs.unshift({
      timestamp: new Date().toLocaleTimeString(),
      message,
      type
    });
  }

  getLogs() {
    return this.logs;
  }

  clearLogs() {
    this.logs = [];
  }

  /**
   * Transforms a remote operation against local pending operations.
   * Implementation of Operational Transformation for Docs, Sheets, and Slides.
   */
  transform(localOp, remoteOp) {
    // If different targets, no conflict
    if (localOp.targetId !== remoteOp.targetId && localOp.type !== 'text') {
      return { localOp, remoteOp, conflict: false };
    }

    let conflict = false;

    // --- DOCS TEXT EDIT CONFLICT ---
    if (localOp.type === 'text' && remoteOp.type === 'text') {
      const l = { ...localOp };
      const r = { ...remoteOp };
      
      if (l.action === 'insert' && r.action === 'insert') {
        if (l.index === r.index) {
          conflict = true;
          // Tie-breaker based on client ID priority
          if (l.clientId < r.clientId) {
            r.index += l.text.length;
            this.log(`Text collision at index ${l.index}! Client ${l.username} wins. Transformed ${r.username}'s insertion index to ${r.index}.`, 'conflict');
          } else {
            l.index += r.text.length;
            this.log(`Text collision at index ${l.index}! Client ${r.username} wins. Transformed local insertion index to ${l.index}.`, 'conflict');
          }
        } else if (l.index < r.index) {
          r.index += l.text.length;
        } else {
          l.index += r.text.length;
        }
      }
      return { localOp: l, remoteOp: r, conflict };
    }

    // --- SHEETS CELL EDIT CONFLICT ---
    if (localOp.type === 'cell' && remoteOp.type === 'cell') {
      const l = { ...localOp };
      const r = { ...remoteOp };

      if (l.cellId === r.cellId) {
        conflict = true;
        // Last-write-wins based on timestamp or client ID
        if (l.timestamp >= r.timestamp) {
          this.log(`Cell collision on ${l.cellId}! Local update ("${l.value}") overrides ${r.username}'s concurrent update ("${r.value}") based on timestamp.`, 'conflict');
        } else {
          this.log(`Cell collision on ${l.cellId}! ${r.username}'s update ("${r.value}") overrides local update ("${l.value}").`, 'conflict');
        }
      }
      return { localOp: l, remoteOp: r, conflict };
    }

    // --- SLIDES ELEMENT EDIT CONFLICT ---
    if (localOp.type === 'slide-element' && remoteOp.type === 'slide-element') {
      const l = { ...localOp };
      const r = { ...remoteOp };

      if (l.slideId === r.slideId && l.elementId === r.elementId) {
        conflict = true;
        // Merge position changes or choose one
        this.log(`Slide collision on Element ${l.elementId}! Merged concurrent drags. Local movement (X:${l.x}, Y:${l.y}) merged with ${r.username}'s concurrent drag (X:${r.x}, Y:${r.y}).`, 'conflict');
        
        // Simple blend of movements to simulate merge
        r.x = Math.round((l.x + r.x) / 2);
        r.y = Math.round((l.y + r.y) / 2);
        l.x = r.x;
        l.y = r.y;
      }
      return { localOp: l, remoteOp: r, conflict };
    }

    return { localOp, remoteOp, conflict };
  }

  /**
   * Simulates sending operations to the central server and receiving syncs.
   * @param {Object} localOp - The operation generated by the local user.
   * @param {Array} concurrentRemoteOps - Operations generated by simulated bots.
   * @returns {Object} { transformedLocalOp, transformedRemoteOps, finalRevision }
   */
  sync(localOp, concurrentRemoteOps = []) {
    let finalLocalOp = localOp ? { ...localOp } : null;
    const finalRemoteOps = concurrentRemoteOps.map(op => ({ ...op }));
    
    this.revision++;
    const currentRev = this.revision;
    this.log(`Sync Sequence Triggered. Advancing server revision to ${currentRev}.`, 'sync');

    if (finalLocalOp) {
      this.log(`Local user generated operation: ${JSON.stringify(finalLocalOp)}`, 'info');
    }

    // Transform all concurrent edits against each other
    for (let i = 0; i < finalRemoteOps.length; i++) {
      const remote = finalRemoteOps[i];
      this.log(`Concurrent remote operation received from ${remote.username}: ${JSON.stringify(remote)}`, 'info');
      
      if (finalLocalOp) {
        const { localOp: lTrans, remoteOp: rTrans, conflict } = this.transform(finalLocalOp, remote);
        finalLocalOp = lTrans;
        finalRemoteOps[i] = rTrans;
        if (!conflict) {
          this.log(`Operations merged without conflicts. Both clients synced to revision ${currentRev}.`, 'sync');
        }
      }
    }

    return {
      localOp: finalLocalOp,
      remoteOps: finalRemoteOps,
      revision: currentRev
    };
  }
}
